#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$ROOT/skills/_shared/lib.sh"

if [[ $# -lt 1 ]]; then
  echo "usage: brain-consolidate <instruction.json>" >&2
  exit 2
fi

instruction="$1"
[[ -f "$instruction" ]] || { echo "missing $instruction" >&2; exit 2; }

# Need jq; if absent, fail loudly
command -v jq >/dev/null || { echo "jq required" >&2; exit 3; }

brain_pull "$OPERATIONAL_DIR"

date_str="$(jq -r .date "$instruction")"
[[ "$date_str" == "$(today)" ]] || { echo "instruction date $date_str != today $(today)" >&2; exit 4; }

# Process project updates
proj_count=$(jq '.project_updates | length' "$instruction")
for i in $(seq 0 $((proj_count - 1))); do
  slug=$(jq -r ".project_updates[$i].slug" "$instruction")
  title=$(jq -r ".project_updates[$i].title" "$instruction")
  status=$(jq -r ".project_updates[$i].status" "$instruction")
  create=$(jq -r ".project_updates[$i].create_if_missing" "$instruction")
  proj_file="$OPERATIONAL_DIR/projects/$slug.md"

  if [[ ! -f "$proj_file" && "$create" == "true" ]]; then
    cat > "$proj_file" <<EOF
---
title: $title
slug: $slug
status: $status
created: $(today)
updated: $(today)
last_touched: $(today)
due: null
related: []
---

## Summary
*(to be filled in)*

## Open Loops

## Done

## Notes

## Cross-references
EOF
  fi

  # Update frontmatter status, updated, last_touched
  python3 - "$proj_file" "$status" "$(today)" <<'PY'
import sys, re, pathlib
p = pathlib.Path(sys.argv[1])
status, today = sys.argv[2], sys.argv[3]
text = p.read_text()
text = re.sub(r'^status:.*$', f'status: {status}', text, count=1, flags=re.M)
text = re.sub(r'^updated:.*$', f'updated: {today}', text, count=1, flags=re.M)
text = re.sub(r'^last_touched:.*$', f'last_touched: {today}', text, count=1, flags=re.M)
p.write_text(text)
PY

  # Append Open Loops
  ol_count=$(jq ".project_updates[$i].append_open_loops | length" "$instruction")
  for j in $(seq 0 $((ol_count - 1))); do
    line=$(jq -r ".project_updates[$i].append_open_loops[$j]" "$instruction")
    python3 - "$proj_file" "$line" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1])
line = sys.argv[2]
text = p.read_text()
text = text.replace('## Open Loops\n', f'## Open Loops\n- {line}\n', 1)
p.write_text(text)
PY
  done

  # Append Done
  d_count=$(jq ".project_updates[$i].append_done | length" "$instruction")
  for j in $(seq 0 $((d_count - 1))); do
    line=$(jq -r ".project_updates[$i].append_done[$j]" "$instruction")
    python3 - "$proj_file" "$line" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1])
line = sys.argv[2]
text = p.read_text()
text = text.replace('## Done\n', f'## Done\n- {line}\n', 1)
p.write_text(text)
PY
  done
done

# Daily done
daily_file="$OPERATIONAL_DIR/daily/$(today).md"
if [[ ! -f "$daily_file" ]]; then
  cat > "$daily_file" <<EOF
# $(today)

## Intent

## Done

## Notes
EOF
fi
dd_count=$(jq '.daily_done | length' "$instruction")
for j in $(seq 0 $((dd_count - 1))); do
  line=$(jq -r ".daily_done[$j]" "$instruction")
  python3 - "$daily_file" "$line" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1])
line = sys.argv[2]
text = p.read_text()
text = text.replace('## Done\n', f'## Done\n- {line}\n', 1)
p.write_text(text)
PY
done

# Regenerate _index.md
python3 - "$OPERATIONAL_DIR" <<'PY'
import sys, pathlib, re
op = pathlib.Path(sys.argv[1])
def parse(p):
    text = p.read_text()
    fm = re.search(r'^---\n(.*?)\n---', text, re.S | re.M)
    if not fm: return None
    fields = {}
    for line in fm.group(1).splitlines():
        if ':' in line:
            k, v = line.split(':', 1)
            fields[k.strip()] = v.strip()
    return fields

projects = sorted(op.glob('projects/*.md'))
areas = sorted(op.glob('areas/*.md'))

lines = ['# Operational Wiki — Index', '', '*Auto-generated by `/brain-consolidate` and `/brain-process`. Do not hand-edit.*', '', '## Projects', '']
if not projects:
    lines.append('*(no projects yet)*')
for p in projects:
    f = parse(p) or {}
    title = f.get('title', p.stem)
    status = f.get('status', '?')
    summary_match = re.search(r'## Summary\n(.+?)(\n##|\Z)', p.read_text(), re.S)
    summary = (summary_match.group(1).strip().splitlines()[0] if summary_match else '').strip().lstrip('*').strip()
    lines.append(f'- [{title}](projects/{p.name}) — {status} — {summary}')

lines += ['', '## Areas', '']
if not areas:
    lines.append('*(no areas yet)*')
for a in areas:
    f = parse(a) or {}
    title = f.get('title', a.stem)
    status = f.get('status', '?')
    summary_match = re.search(r'## Summary\n(.+?)(\n##|\Z)', a.read_text(), re.S)
    summary = (summary_match.group(1).strip().splitlines()[0] if summary_match else '').strip().lstrip('*').strip()
    lines.append(f'- [{title}](areas/{a.name}) — {status} — {summary}')

(op / '_index.md').write_text('\n'.join(lines) + '\n')
PY

brain_log "brain-consolidate" "instruction $(basename "$instruction")"
brain_commit_push "$OPERATIONAL_DIR" "brain-consolidate: $(today)"
echo "consolidated"
